version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "7070:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/access.log:/var/log/nginx/acces.log
      - ./logs/error.log:/var/log/nginx/error.log
    links:
      - php

  php:
    image: php:fpm-bullseye
#    build:
#      context: ./php
#      dockerfile: dockerfile
    volumes:
      - ./www:/var/www/html
    expose:
      - 9000
    