version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - "7071:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/
    links:
      - php

  php:
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./www:/var/www/html
    expose:
      - 9000
    env_file:
      - .env
    